### ISSUE TITLE
Multiple CSS Selectors

### ISSUE THREAD

**Issue by cyouh95** [freden29/prj-rev-bwfs-dasmoto#1]
Alternatively, you can specify shared properties for multiple elements by including all the selectors separated by commas:

```css
h1, h2, span {
  font-family: Helvetica;
}
```

https://github.com/freden29/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/resources/styles.css
